# Generated by Django 4.1 on 2022-08-06 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Product:')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity:')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Additional price')),
                ('additional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='additional_product_group',
            field=models.ManyToManyField(blank=True, to='app_shop.quantityproduct'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ManyToManyField(to='app_shop.orderitem')),
            ],
        ),
    ]
